[package]
name = "todo"
version = "0.1.0"
authors = ["Simeon <simeon.anfinrud@mac.com>"]

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
ansi_term = "0.12"
atty = "0.2"
chrono = { version = "0.4", features = ["serde"] }
directories = "4.0"
humantime = "2.1"
itertools = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }
term_size = "0.3"
thiserror = "1.0.30"
textwrap = "0.15.0"

clock = { path = "./clock" }
config = { path = "./config" }
lookup_key = { path = "./lookup_key" }
long_output = { path = "./long_output" }
model = { path = "./model" }
text_editing = { path = "./text_editing" }
time_format = { path = "./time_format" }

[workspace]
members = [
    "clock",
    "config",
    "lookup_key",
    "long_output",
    "model",
    "text_editing",
    "time_format",
]