[package]
name = "todo-lib"
version = "0.1.0"
authors = ["Simeon <simeon.anfinrud@mac.com>"]

[dependencies]
clap = "~2.33.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
