[package]
name = "todo"
version = "0.1.0"
authors = ["Simeon <simeon.anfinrud@mac.com>"]

[dependencies]
ansi_term = "0.12"
chrono = { version = "0.4", features = ["serde"] }
app_dirs = "1.2.1"
daggy = { version = "0.7", features = ["serde-1", "stable_dag"] }
itertools = "0.10"
scrawl = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }
term_size = "0.3"
textwrap = "0.13"