[package]
name = "todo"
version = "0.1.0"
authors = ["Simeon <simeon.anfinrud@mac.com>"]

[dependencies]
ansi_term = "0.12"
chrono = { version = "0.4", features = ["serde"] }
clap = "~2.33.0"
app_dirs = "1.2.1"
daggy = { version = "*", features = ["serde-1"] }
itertools = "0.10.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
structopt = { version = "0.3.21", default-features = false }
