[package]
name = "todo"
version = "0.1.0"
authors = ["Simeon <simeon.anfinrud@mac.com>"]

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
ansi_term = "0.12"
atty = "0.2"
bisection = "0.1"
chrono = { version = "0.4", features = ["serde"] }
directories = "4.0"
daggy = { version = "0.8", features = ["serde-1", "stable_dag"] }
humantime = "2.1"
itertools = "0.10"
scrawl = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }
term_size = "0.3"
textwrap = "0.14"