[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
directories = "4.0"
structopt = { version = "0.3", default-features = false }
term_size = "0.3"
thiserror = "1.0.30"

clock = { path = "../clock" }
config = { path = "../config" }
long_output = { path = "../long_output" }
model = { path = "../model" }
printing = { path = "../printing" }
text_editing = { path = "../text_editing" }
todo = { path = ".." }