[package]
name = "todo_main"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true

todo_app.workspace = true
todo_builtin_apps.workspace = true
todo_cli.workspace = true
todo_runner.workspace = true
