[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.*"
directories = "4.0"
term_size = "0.3"
thiserror = "1.0.30"

app = {path = "../app" }
cli = { path = "../cli" }
clock = { path = "../clock" }
config = { path = "../config" }
model = { path = "../model" }
printing = { path = "../printing" }
text_editing = { path = "../text_editing" }
