[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo_clock.workspace = true
todo_model.workspace = true
todo_printing.workspace = true
todo_text_editing.workspace = true
