[package]
name = "printing"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
chrono = { version = "0.4", features = ["serde"] }
textwrap = "0.15.0"

lookup_key = { path = "../lookup_key" }
time_format = { path = "../time_format" }
testing = { path = "../testing" }