[package]
name = "todo_printing"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term.workspace = true
chrono.workspace = true
textwrap.workspace = true

todo_lookup_key.workspace = true
todo_time_format.workspace = true
todo_testing.workspace = true