[package]
name = "printing"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term.workspace = true
chrono.workspace = true
textwrap.workspace = true

lookup_key.workspace = true
time_format.workspace = true
testing.workspace = true